---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ion.fullname" . }}-biz
  labels:
    {{- include "ion.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ion.name" . }}-biz
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ion.name" . }}-biz
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-biz
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.biz.image.pullPolicy }}
          image: {{ .Values.biz.image.repository }}:{{ .Values.biz.image.tag}} 
          command: ["/usr/local/bin/biz", "-c", "/configs/biz.toml"]
          resources:
            requests:
              cpu: 500m 
              memory: 200Mi
              #            limits:
              #              cpu: 500m
              #              memory: 500Mi
          env:
            - name: SERVICE
              value: biz
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - name: config-volume
            mountPath: /configs/
          ports:
          - name: biz
            containerPort: 8443
            protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ include "ion.fullname" . }}-config

