apiVersion: v1
kind: Service
metadata:
  name: {{ include "ion.fullname" . }}-biz
  labels:
    {{- include "ion.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: biz
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ion.name" . }}-biz
    app.kubernetes.io/instance: {{ .Release.Name }}


