apiVersion: v1
kind: Service
metadata:
  name: {{ include "ion.fullname" . }}-web
  labels:
    {{- include "ion.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 80   
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ion.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}

